### ISSUE TITLE
Not working in Mono/Turborepo

### ISSUE THREAD

**Issue by ericwaetke** [OrJDev/create-jd-app#109]
Hi,
I've got the following error when trying to use Solid Start with SSR in my Turborepo

```
An unhandled error occured: TypeError: __vite_ssr_import_3__.getRequestEvent is not a function
    at MetaProvider (...project\node_modules\.pnpm\@solidjs+meta@0.29.1_solid-js@1.8.3\node_modules\@solidjs\meta\dist\index.jsx:147:16)
    at Proxy.createComponent (file:///...project/node_modules/.pnpm/solid-js@1.8.3/node_modules/solid-js/dist/server.js:349:15)
    at get children [as children] (...project\node_modules\.pnpm\solid-start@0.3.7_@solidjs+meta@0.29.1_@solidjs+router@0.8.3_solid-js@1.8.3_solid-start-node@_rjluhh2athxyzueup5iy4wratm\node_modules\solid-start\entry-server\StartServer.tsx:86:16)
    at file:///...project/node_modules/.pnpm/solid-js@1.8.3/node_modules/solid-js/dist/server.js:216:35
    at file:///...project/node_modules/.pnpm/solid-js@1.8.3/node_modules/solid-js/dist/server.js:179:49
    at createMemo (file:///...project/node_modules/.pnpm/solid-js@1.8.3/node_modules/solid-js/dist/server.js:95:9)
    at children (file:///...project/node_modules/.pnpm/solid-js@1.8.3/node_modules/solid-js/dist/server.js:179:16)
    at file:///...project/node_modules/.pnpm/solid-js@1.8.3/node_modules/solid-js/dist/server.js:216:14
    at createMemo (file:///...project/node_modules/.pnpm/solid-js@1.8.3/node_modules/solid-js/dist/server.js:95:9)
    at provider (file:///...project/node_modules/.pnpm/solid-js@1.8.3/node_modules/solid-js/dist/server.js:211:12)
    at Proxy.createComponent (file:///...project/node_modules/.pnpm/solid-js@1.8.3/node_modules/solid-js/dist/server.js:349:15)
    at StartServer (...project\node_modules\.pnpm\solid-start@0.3.7_@solidjs+meta@0.29.1_@solidjs+router@0.8.3_solid-js@1.8.3_solid-start-node@_rjluhh2athxyzueup5iy4wratm\node_modules\solid-start\entry-server\StartServer.tsx:81:3)
    at Proxy.createComponent (file:///...project/node_modules/.pnpm/solid-js@1.8.3/node_modules/solid-js/dist/server.js:349:15)
    at ...project\apps\backend-ssr\src\entry-server.tsx:8:21
    at ...project\node_modules\.pnpm\solid-start@0.3.7_@solidjs+meta@0.29.1_@solidjs+router@0.8.3_solid-js@1.8.3_solid-start-node@_rjluhh2athxyzueup5iy4wratm\node_modules\solid-start\server\render.ts:63:50
    at file:///...project/node_modules/.pnpm/solid-js@1.8.3/node_modules/solid-js/web/dist/server.js:254:34
    at createRoot (file:///...project/node_modules/.pnpm/solid-js@1.8.3/node_modules/solid-js/dist/server.js:58:14)
    at renderToStream (file:///...project/node_modules/.pnpm/solid-js@1.8.3/node_modules/solid-js/web/dist/server.js:252:14)
    at Proxy.renderToStringAsync (file:///...project/node_modules/.pnpm/solid-js@1.8.3/node_modules/solid-js/web/dist/server.js:114:24)
    at ...project\node_modules\.pnpm\solid-start@0.3.7_@solidjs+meta@0.29.1_@solidjs+router@0.8.3_solid-js@1.8.3_solid-start-node@_rjluhh2athxyzueup5iy4wratm\node_modules\solid-start\server\render.ts:63:24
    at ...project\node_modules\.pnpm\solid-start@0.3.7_@solidjs+meta@0.29.1_@solidjs+router@0.8.3_solid-js@1.8.3_solid-start-node@_rjluhh2athxyzueup5iy4wratm\node_modules\solid-start\server\middleware.ts:90:28
    at ...project\node_modules\.pnpm\solid-start@0.3.7_@solidjs+meta@0.29.1_@solidjs+router@0.8.3_solid-js@1.8.3_solid-start-node@_rjluhh2athxyzueup5iy4wratm\node_modules\solid-start\api\middleware.ts:38:18
    at ...project\node_modules\.pnpm\solid-start@0.3.7_@solidjs+meta@0.29.1_@solidjs+router@0.8.3_solid-js@1.8.3_solid-start-node@_rjluhh2athxyzueup5iy4wratm\node_modules\solid-start\entry-server\StartServer.tsx:50:7
    at devFetch (file:///...project/node_modules/.pnpm/solid-start@0.3.7_@solidjs+meta@0.29.1_@solidjs+router@0.8.3_solid-js@1.8.3_solid-start-node@_rjluhh2athxyzueup5iy4wratm/node_modules/solid-start/dev/server.js:111:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startHandler (file:///...project/node_modules/.pnpm/solid-start@0.3.7_@solidjs+meta@0.29.1_@solidjs+router@0.8.3_solid-js@1.8.3_solid-start-node@_rjluhh2athxyzueup5iy4wratm/node_modules/solid-start/dev/server.js:134:20)
```

I'm using pnpm (nothing else quite workes with my turborepo setup), and installed the latest version of create-jd-app.
This happens regardless of the configuration of create-jd-app. Doesn't matter if I'm using the vercel adapter or not. Also doesn't matter if I choose to install any of the additional packages like trpc.

When disabling ssr in the vite.config.ts, I get a similar error in the client console: `Uncaught SyntaxError: ambiguous indirect export: getRequestEvent`

I've had a ton of problems with solidstart in a turbo repo in general, but I've got working envs with the 2.30 solid-start version.
I tried to update as I get `renderToString timed out` on every first(?) request/coldstart.

**Comment by OrJDev** [comment]
Please try in the latest version and lmk if that works
