### ISSUE TITLE
Could not resolve ".prisma/client/index-browser"

### ISSUE THREAD

**Issue by neolivz** [OrJDev/create-jd-app#67]
When you run a new project I get the error
```
GET http://localhost:3000/api/trpc/example.hello?batch=1&input=%7B%220%22%3A%7B%22name%22%3A%22from%20tRPC%22%7D%7D
✘ [ERROR] Could not resolve ".prisma/client/index-browser"

    node_modules/@prisma/client/index-browser.js:1:23:
      1 │ const prisma = require('.prisma/client/index-browser')
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing ".prisma" here because it's not listed as a
  dependency of this package:

    ../../.pnp.cjs:45:33:
      45 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path ".prisma/client/index-browser" as external to exclude it from the bundle,
  which will remove this error. You can also surround this "require" call with a try/catch block
  to handle this failure at run-time instead of bundle-time.
  ```

**Comment by OrJDev** [comment]
what is your vite config?
also what command are you trying to run

**Comment by neolivz** [comment]
node --version
v18.14.0

npm --version
9.3.1


I ran
```
npm create jd-app@latest
```

```
npm create jd-app@latest

? What is the name of the app? my-app
? Will you deploy this project to vercel? If so, how None

✔ Copied template files to /Users/jishnu/Work/rnd/solidjs/my-app
? What should we use for this app? AuthJS, Prisma, TailwindCSS, pRPC

✔ Initialized 4 installers
✔ Modified project

Using NPM as package manager
✔ Installed dependencies
✔ Ran queued commands
```
```
cd my-app
npm run push
npm run dev
```

Throws error
```
GET http://127.0.0.1:3000/api/trpc/example.hello?batch=1&input=%7B%220%22%3A%7B%22name%22%3A%22from%20tRPC%22%7D%7D
✘ [ERROR] Could not resolve ".prisma/client/index-browser"

    node_modules/@prisma/client/index-browser.js:1:23:
      1 │ const prisma = require('.prisma/client/index-browser')
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing ".prisma" here because it's not listed as a
  dependency of this package:

    ../../.pnp.cjs:45:33:
      45 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path ".prisma/client/index-browser" as external to exclude it from the bundle,
  which will remove this error. You can also surround this "require" call with a try/catch block
  to handle this failure at run-time instead of bundle-time.

10:49:28 am [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@prisma/client/index-browser.js:1:23: ERROR: Could not resolve ".prisma/client/index-browser"
    at failureErrorWithLog (/Users/jishnu/Work/rnd/solidjs/my-app/node_modules/vite/node_modules/esbuild/lib/main.js:1604:15)
    at /Users/jishnu/Work/rnd/solidjs/my-app/node_modules/vite/node_modules/esbuild/lib/main.js:1056:28
    at runOnEndCallbacks (/Users/jishnu/Work/rnd/solidjs/my-app/node_modules/vite/node_modules/esbuild/lib/main.js:1476:61)
    at buildResponseToResult (/Users/jishnu/Work/rnd/solidjs/my-app/node_modules/vite/node_modules/esbuild/lib/main.js:1054:7)
    at /Users/jishnu/Work/rnd/solidjs/my-app/node_modules/vite/node_modules/esbuild/lib/main.js:1166:14
    at responseCallbacks.<computed> (/Users/jishnu/Work/rnd/solidjs/my-app/node_modules/vite/node_modules/esbuild/lib/main.js:701:9)
    at handleIncomingPacket (/Users/jishnu/Work/rnd/solidjs/my-app/node_modules/vite/node_modules/esbuild/lib/main.js:756:9)
    at Socket.readFromStdout (/Users/jishnu/Work/rnd/solidjs/my-app/node_modules/vite/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by OrJDev** [comment]
that is weird, what is your vite config?

**Comment by OrJDev** [comment]
please reopen when you are free to answer some questions, i can't help much with that info.
