### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by CMeyer19** [OrJDev/create-jd-app#71]
From what I can tell this an issue from release v0.1.25 up to the latest (at the time of creating this: v0.1.27)

? What is the name of the app? my-app
? Will you deploy this project to vercel? If so, how None
? What should we use for this app? TailwindCSS, tRPC
? Do you want to use SSR with tRPC? Yes
- cd my-app
- npm run dev

Then open http://127.0.0.1:3000/ in browser

You will then be presented with an error saying: 
`TRPCClientError: Unexpected token < in JSON at position 0
    at Function.from (file:///***/node_modules/@trpc/client/dist/transformResult-6fb67924.mjs:13:16)
    at file:///***/node_modules/@trpc/client/dist/links/httpBatchLink.mjs:200:64
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  meta: undefined,
  shape: undefined,
  data: undefined,
  [cause]: SyntaxError: Unexpected token < in JSON at position 0
      at JSON.parse (<anonymous>)
      at parseJSONFromBytes (***\node_modules\undici\lib\fetch\body.js:572:15)
      at successSteps (***\node_modules\undici\lib\fetch\body.js:512:23)
      at ***\node_modules\undici\lib\fetch\util.js:814:56
      at node:internal/process/task_queues:141:7
      at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
      at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
}`

From my investigation this is due to a change in directory:
From: src\routes\api\trpc\\[trpc].ts
To: src\routes\api\\[trpc].ts

**I was able to fix the issue in the generated project by making the following change:**
File: src\utils\trpc.ts
Line: 19
From: "url: `${getBaseUrl()}/api/trpc`,"
To: "url: `${getBaseUrl()}/api`,"

The changes required to this repo are:
src\installers\tRPC\files\utils.txt (line 16): url: `${getBaseUrl()}/api/trpc`, => url: `${getBaseUrl()}/api`,
src\installers\tRPC\files\ssr-utils.txt (line 19): url: `${getBaseUrl()}/api/trpc`, => url: `${getBaseUrl()}/api`,

**Comment by OrJDev** [comment]
fixed in https://github.com/OrJDev/create-jd-app/commit/51d0ae08fbbe0bc5294932512c590cab6bc94bc6
