### ISSUE TITLE
Application not starting

### ISSUE THREAD

**Issue by neolivz** [OrJDev/create-jd-app#94]
I created a new project with node 18.14.0

? Will you deploy this project to vercel? If so, how None

✔ Copied template files to /Users/neolivz/Work/rnd/t3/solid-dummy-flight
? What should we use for this app? AuthJS, TailwindCSS, tRPC
? Do you want to use SSR with tRPC? Yes

When I run npm run dev I get error
```
TypeError: Cannot read properties of undefined (reading 'type')
    at QueryObserver.onQueryUpdate (/node_modules/solid-trpc/dist/index.js:2573:16)
    at file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/@tanstack/query-core/build/lib/query.mjs:389:18
    at Array.forEach (<anonymous>)
    at file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/@tanstack/query-core/build/lib/query.mjs:388:23
    at Object.batch (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/@tanstack/query-core/build/lib/notifyManager.mjs:18:16)
    at #dispatch (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/@tanstack/query-core/build/lib/query.mjs:387:19)
    at Query.fetch (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/@tanstack/query-core/build/lib/query.mjs:238:21)
    at #executeFetch (/node_modules/solid-trpc/dist/index.js:2341:38)
    at QueryObserver.onSubscribe (/node_modules/solid-trpc/dist/index.js:2227:27)
    at QueryObserver.subscribe (/node_modules/solid-trpc/dist/index.js:1343:10)
    at createServerSubscriber (/node_modules/solid-trpc/dist/index.js:3090:21)
    at eval (/node_modules/solid-trpc/dist/index.js:3136:23)
    at new Promise (<anonymous>)
    at __vite_ssr_import_1__.createResource.initialValue (/node_modules/solid-trpc/dist/index.js:3134:12)
    at load (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:488:11)
    at Proxy.createResource (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:516:42)
    at createBaseQuery (/node_modules/solid-trpc/dist/index.js:3133:30)
    at createQuery (/node_modules/solid-trpc/dist/index.js:3220:10)
    at Object.useQuery (/node_modules/solid-trpc/dist/index.js:3398:12)
    at eval (/node_modules/solid-trpc/dist/index.js:1269:26)
    at Object.apply (/node_modules/solid-trpc/dist/index.js:646:14)
    at Home (/src/routes/index.tsx:25:58)
    at Proxy.createComponent (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:310:15)
    at shared.element.component.element.element [as outlet] (/node_modules/@solidjs/router/dist/routing.js:87:43)
    at get children [as children] (/node_modules/@solidjs/router/dist/components.jsx:102:22)
    at file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:213:35
    at file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:174:49
    at createMemo (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:83:9)
    at children (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:174:16)
    at file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:213:14
    at createMemo (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:83:9)
    at provider (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:209:12)
    at Proxy.createComponent (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:310:15)
    at children (/node_modules/@solidjs/router/dist/components.jsx:99:46)
    at Show (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:375:68)
    at Proxy.createComponent (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:310:15)
    at Routes (/node_modules/@solidjs/router/dist/components.jsx:94:32)
    at Proxy.createComponent (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:310:15)
    at get children [as children] (/src/root.tsx:53:56)
    at get children [as children] (/node_modules/solid-start/error-boundary/ErrorBoundary.tsx:32:20)
    at error (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:412:41)
    at catchError (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:141:12)
    at file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:412:12
    at createMemo (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:83:9)
    at ErrorBoundary (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:410:3)
    at Proxy.createComponent (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:310:15)
    at ErrorBoundary (/node_modules/solid-start/error-boundary/ErrorBoundary.tsx:15:32)
    at Proxy.createComponent (file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:310:15)
    at get children [as children] (/src/root.tsx:51:52)
    at file:///Users/neolivz/Work/rnd/t3/solid-dummy-flight/node_modules/solid-js/dist/server.js:616:39
    ```

**Comment by OrJDev** [comment]
Can you try upgrading to the latest version of solid query?

```
npm install @tanstack/solid-query@alpha
```

**Comment by OrJDev** [comment]
This issue was fixed in https://github.com/OrJDev/create-jd-app/commit/92b6ec6ba94678895fb7b213f47c7941ace75455

You can fix it on your end by running:

```sh
pnpm install @tanstack/solid-query@5.0.0-alpha.20
```
